apiVersion: v2
name: service-mesh
description: A Helm chart for installing istio service mesh

type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: kiali-server
    version: 2.5.*
    repository: https://kiali.org/helm-charts
    condition: kiali-server.enabled
  - name: jaeger
    version: 3.4.*
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
  - name: base
    version: 1.25.*
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.25.*
    repository: https://istio-release.storage.googleapis.com/charts