kiali-server:
  enabled: true
  istio_namespace: "istio-system"
  auth:
    strategy: anonymous

jaeger:
  fullnameOverride: ""
  enabled: true
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

  storage:
    type: memory
    cassandra:
      createSchema: false
    elasticsearch:
      createIndex: false
    kafka:
      createTopic: false
    memory:
      maxTraces: 100000
    spanStorageType: memory


base:
  defaultRevision: default